CREATE TABLE ARCHIVE_EMPLOYEE AS 
SELECT * FROM EEMPLOYEES 
WHERE HIRE_DATE < TO_DATE('01-01-2008', 'DD-MM-YYYY');



DELETE FROM EEMPLOYEE
WHERE HIRE_DATE < TO_DATE('01-01-2008', 'DD-MM-YYYY');


DELETE FROM EMPLOYEES WHERE HIRE_DATE < TO_DATE('01-01-2008', 'DD-MM-YYYY');

ROLLBACK;

\

-- CREATING PROCEDURE FOR ARCHIVE THE DATA FROM TABLE




CREATE OR REPLACE PROCEDURE CREATING IS
BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE ARCHIVE_EEMPLOYEES AS 
                           SELECT * FROM EEMPLOYEES 
                           WHERE HIRE_DATE < TO_DATE(''01-01-2008'', ''DD-MM-YYYY'')'; 
                            
        EXECUTE IMMEDIATE 'DELETE FROM EEMPLOYEES
                           WHERE HIRE_DATE < TO_DATE(''01-01-2008'', ''DD-MM-YYYY'')';
END;
/


EXEC CREATING;


SELECT * FROM EEMPLOYEES;
SELECT * FROM ARCHIVE_EEMPLOYEES;


CREATE OR REPLACE PROCEDURE DELETING IS
BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE ARCHIVE_EEMPLOYEES'; 
                            
        EXECUTE IMMEDIATE 'DROP TABLE EEMPLOYEES';
        
        EXECUTE IMMEDIATE 'CREATE TABLE EEMPLOYEES AS SELECT * FROM EMPLOYEES';
END;
/


EXEC DELETING;




CREATE TABLE EMPLOYEESS AS SELECT * FROM EMPLOYEES;

CREATE OR REPLACE PROCEDURE PERCENT(PARADEPARTMENT_ID IN NUMBER)
IS
UPDATEDE EMPLOYEESS.DEPARTMENT_ID%TYPE;
BEGIN
-- DEPARTMENT_ID CHECKING

SELECT DEPARTMENT_ID INTO UPDATED FROM EEMPLOYEES;

IF DEPARTMENT_ID IN UPDATEDE  THEN
    DBMS_OUTPUT.PUT_LINE (' THE DEPARTMENT_ID IS IN THE DEPARTMENT_ID COLUMN '|| DEPARTMENT_ID);
ELSE
    DBMS_OUTPUT.PUT_LINE (' THE DEPARTMENT_ID IS NOT IN THE DEPARTMENT_ID COLUMN '|| DEPARTMENT_ID);
    RAISE ;
END IF;

UPDATE TABLE EMPLOYEESS
SET SALARY = SALARY + SALARY * .05
WHERE DEPARTMENT_ID = PARADEPARTMENT_ID;
DBMS_OUTPUT.PUT_LINE ('UPADTED SUCCESSFULLY IN '|| DEPARTMENT_ID);
END;
/



=========================================






CREATE OR REPLACE PROCEDURE PERCENT(PARADEPARTMENT_ID IN NUMBER)
IS
    V_COUNT NUMBER;
BEGIN
    -- Check if the department ID exists
    SELECT COUNT(*) INTO V_COUNT
    FROM EMPLOYEESS
    WHERE DEPARTMENT_ID = PARADEPARTMENT_ID;
    IF V_COUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE('THE DEPARTMENT_ID ' || PARADEPARTMENT_ID || ' EXISTS.');
        -- Update salary by 5% for that department
        UPDATE EMPLOYEESS
        SET SALARY = SALARY + SALARY * 0.05
        WHERE DEPARTMENT_ID = PARADEPARTMENT_ID;
        DBMS_OUTPUT.PUT_LINE('UPDATED SUCCESSFULLY FOR DEPARTMENT_ID: ' || PARADEPARTMENT_ID);
    ELSE
        -- Department ID does not exist, raise an exception
        RAISE_APPLICATION_ERROR(-20001, 'THE DEPARTMENT_ID ' || PARADEPARTMENT_ID || ' DOES NOT EXIST IN THE TABLE.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END;
/


BEGIN
PERCENT(99);
END;
/

SELECT * FROM EMPLOYEESS WHERE DEPARTMENT_ID = 90;