-- WITH CLAUSS
--      a qury act as a temprory table 

-- You want to find the top 5 highest-paid employees in the company.

select first_name,salary,rank() over (order by salary desc) as rank from employees 
where rank between 1 and 5;

with fun as (select first_name,salary,rank() over (order by salary desc) as arank 
from employees)
select first_name,salary,arank from fun where arank <=5;

-- Subquery

-- IT IS A QUERY (OR) SELECT QUERY INSIDE A QUERY
-- QUERY IMPROVE THE PERFORMENCE AND MAINTAIN

TYPES OF SUBQUERY
        -- SINGLE ROW
        -- MULTI ROW
        -- SCALOR
        -- INLINE 
        -- NESTED
        -- CORRELATED
        -- MULTI COLUMN

-- SINGLE ROW SUB QUERY

-- A SUB QUERY RETURNING A ROW/VALUE
-- SYNTAX FOR SINGLE ROW
--SELECT COL1,COL2 FROM TABLE WHERE CONDITION ( SELECT COL1 FROM TABLE WHERE CONDITION );

SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE FIRST_NAME='Lex';--17000

SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE SALARY > 17000;

SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE SALARY > 
( SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME='Lex' );

=,!=,<,>

-- Multirow Sub Query

-- A SUB QUERY RETURNING A MULTIPLE ROW/VALUE
-- IN , NOT IN , ALL , ANY

-- SYNTAX FOR SINGLE ROW
--SELECT COL1,COL2 FROM TABLE 
-- WHERE CONDITION IN,NOT IN,ANY,ALL(SELECT COL1 FROM TABLE WHERE CONDITION);

SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE SALARY <ALL
(SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID=60);

-- Scalar Sub Query
-- A SUB QUERY INSIDE A SELECT CLAUSS
-- A SCALAR SUB QUERY RETURN EXACTLY ONE ROW 
-- IF THE SCALAR SUBQUERY FINDS NOT MATCHED RECORDS IT GIVE NULL
-- IF THE SCALAR SUBQUERY FINDS MORE THAN ONE RECORDS IT WILL GIVE ERROR

SELECT FIRST_NAME,SALARY ,(SELECT MAX(SALARY) FROM EMPLOYEES) AS MAX,
(SELECT MIN(SALARY) FROM EMPLOYEES) AS MIN FROM EMPLOYEES WHERE EMPLOYEE_ID = 108;

SELECT FIRST_NAME,SALARY,MAX(SALARY),MIN(SALARY) FROM EMPLOYEES;
FIRST_NAME,SLAARY,MAX,MIN

SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT MIN(SALARY) FROM EMPLOYEES;

-- INLINE VIEW OR INLINE SUBQUERY
-- A SUB QUERY INSIDE A FROM CLAUSE
-- INLINE VIEW ARE USED TO SIMPLY COMPLEX QUERIES


select rn ,first_name,employee_id 
from(select rownum rn,e.* from employees e ORDER BY EMPLOYEE_ID) G
where rn=5;


-- NESTED SUBQUERY
-- A SUB QUERY INSIDE A WHERE CLAUSE      SAME AS SINGLE ROW OR MULTIROW SUBQUERY

-- CORRELATED
-- IF A SUB QUERY DEPANDS ON OUTER QUERY ( OR )
--     THE OUTPUT DEPENDS ON INNER QUERY


SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID IN ( SELECT DEPARTMENT_ID FROM DEPARTMENTS D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID );

-- MULTICOLUMN SUBQUERY
-- THE SUB QUERY THAT RETURN MORE THAN ONE COLUMN 

SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('SA_REP') AND FIRST_NAME='David'; 


SELECT * FROM EMPLOYEES WHERE (FIRST_NAME,JOB_ID) IN 
(SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES WHERE EMPLOYEE_ID IN (151,165));